base_url = "https://zola-hallo.janbaudisch.dev"
title = "Hallo"

compile_sass = true

highlight_code = false

build_search_index = false

[extra]

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"
